demo:
  auth:
    #host: authServer.com
    port: 8081
    uri: http://${demo.auth.host:localhost}:${demo.auth.port:8081}
  resource:
    host: resourceServer.com
    #port: 8000
    uri: http://${demo.resource.host:localhost}:${demo.resource.port:8000}

spring:
  sql:
    init:
      platform: h2
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:h2:mem:dbtest;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    username: shoulder
    password: shoulder
    driver-class-name: org.h2.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    # 不应使用 UTC 时间，因为 LocalDateTime 带时区，所以最好和系统保持一致 Asia/Shanghai、SQL show variables like '%time_zone%';
    #    url: jdbc:mysql://${MYSQL_ADDR}/shoulder_platform?serverTimezone=Asia/Shanghai&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    #    username: root
    #    password: ${MYSQL_PWD} # 这里使用了系统的环境变量，参见 Spring Boot 的特性
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 127.0.0.1
      #password: ${REDIS_PWD}


shoulder:
  application:
    errorCodePrefix: '0x000b'
    cluster: true
    id: demo4

  crypto:
    local:
      repository: redis # 将加密元数据放入 redis 避免每次重启导致的解密失败

  web:
    handleGlobalException: false
  # ---------------------------- 关注这里 ------------------------------
  security:
    token:
      store: jwt
    auth: # 如果使用者自行实现登录成功、退出成功处理器，则这些配置将失效，使用者实现的优先生效
      type: token # 测试环境这里设置为 token。session 方式已经可以在页面上尝试了！
      responseType: json

  instance:
    type: FIXED
    id: 0
