# demo2 使用 yaml 格式配置作为示例，properties转yaml: https://www.toyaml.com/index.html
spring:
  application:
    name: demo2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      platform: h2
      mode: always
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:h2:mem:dbtest;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    username: shoulder
    password: shoulder
    driver-class-name: org.h2.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    # 不应使用 UTC 时间，因为 LocalDateTime 带时区，所以最好和系统保持一致 Asia/Shanghai、SQL show variables like '%time_zone%';
#    url: jdbc:mysql://${MYSQL_ADDR}/shoulder_platform?serverTimezone=Asia/Shanghai&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=CONVERT_TO_NULL
#    username: root
#    password: ${MYSQL_PWD} # 这里使用了系统的环境变量，参见 Spring Boot 的特性
    type: com.zaxxer.hikari.HikariDataSource

shoulder:
  application:
    errorCodePrefix: '0x000b'
    id: ${spring.application.name}
  web:
    ext:
      tag:
        enable: true
    filter:
      mock:
        userId:
          enable: true
  crypto:
    local:
      # 加密元数据放数据库
      repository: jdbc

  log:
    operation:
      logger:
        # 操作日志放数据库
        type: jdbc

logging:
  level:
    org:
      springframework: warn

debug: false