INSERT INTO user_info (id, name, sex, age, birth, level, id_card, real_name, initials, spellings, phone_num, email, status, group_auth, group_id, group_name, group_path, creator, create_time, update_time, description) VALUES (1, 'shoulder', 0, 21, '2020-01-01', 0, null, null, null, null, null, 'shoulder@shoulder.com', 0, null, null, '', null, 1, '2021-05-15 19:29:06', '2021-05-16 23:43:42', null) ON DUPLICATE KEY UPDATE name = VALUES(name), sex = VALUES(sex), age = VALUES(age), birth = VALUES(birth), level = VALUES(level), id_card = VALUES(id_card), real_name = VALUES(real_name), initials = VALUES(initials), spellings = VALUES(spellings), phone_num = VALUES(phone_num), email = VALUES(email), status = VALUES(status), group_auth = VALUES(group_auth), group_id = VALUES(group_id), group_name = VALUES(group_name), group_path = VALUES(group_path), creator = VALUES(creator), update_time = VALUES(update_time), description = VALUES(description);
INSERT INTO user_info (id, name, sex, age, birth, level, id_card, real_name, initials, spellings, phone_num, email, status, group_auth, group_id, group_name, group_path, creator, create_time, update_time, description) VALUES (2, 'jack', 0, 22, '2020-01-01', 0, null, null, null, null, null, 'jack@shoulder.com', 0, null, null, '', null, 1, '2021-05-15 19:29:06', '2021-05-15 19:29:06', null) ON DUPLICATE KEY UPDATE name = VALUES(name), sex = VALUES(sex), age = VALUES(age), birth = VALUES(birth), level = VALUES(level), id_card = VALUES(id_card), real_name = VALUES(real_name), initials = VALUES(initials), spellings = VALUES(spellings), phone_num = VALUES(phone_num), email = VALUES(email), status = VALUES(status), group_auth = VALUES(group_auth), group_id = VALUES(group_id), group_name = VALUES(group_name), group_path = VALUES(group_path), creator = VALUES(creator), update_time = VALUES(update_time), description = VALUES(description);
INSERT INTO user_info (id, name, sex, age, birth, level, id_card, real_name, initials, spellings, phone_num, email, status, group_auth, group_id, group_name, group_path, creator, create_time, update_time, description) VALUES (3, 'tom', 0, 31, '2020-01-01', 0, null, null, null, null, null, 'tom@shoulder.com', 0, null, null, '', null, 1, '2021-05-15 19:29:06', '2021-05-15 19:29:06', null) ON DUPLICATE KEY UPDATE name = VALUES(name), sex = VALUES(sex), age = VALUES(age), birth = VALUES(birth), level = VALUES(level), id_card = VALUES(id_card), real_name = VALUES(real_name), initials = VALUES(initials), spellings = VALUES(spellings), phone_num = VALUES(phone_num), email = VALUES(email), status = VALUES(status), group_auth = VALUES(group_auth), group_id = VALUES(group_id), group_name = VALUES(group_name), group_path = VALUES(group_path), creator = VALUES(creator), update_time = VALUES(update_time), description = VALUES(description);
INSERT INTO user_info (id, name, sex, age, birth, level, id_card, real_name, initials, spellings, phone_num, email, status, group_auth, group_id, group_name, group_path, creator, create_time, update_time, description) VALUES (4, 'sandy', 0, 33, '2020-01-01', 0, null, null, null, null, null, 'sandy@shoulder.com', 0, null, null, '', null, 1, '2021-05-15 19:29:06', '2021-05-15 19:29:06', null) ON DUPLICATE KEY UPDATE name = VALUES(name), sex = VALUES(sex), age = VALUES(age), birth = VALUES(birth), level = VALUES(level), id_card = VALUES(id_card), real_name = VALUES(real_name), initials = VALUES(initials), spellings = VALUES(spellings), phone_num = VALUES(phone_num), email = VALUES(email), status = VALUES(status), group_auth = VALUES(group_auth), group_id = VALUES(group_id), group_name = VALUES(group_name), group_path = VALUES(group_path), creator = VALUES(creator), update_time = VALUES(update_time), description = VALUES(description);

-- dispatch_platform
TRUNCATE TABLE dispatch_platform;
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', '掘金', 'https://juejin.cn/', '聚焦编程与技术，分享前沿技术、工具资源与经验', '期望获取行业内新鲜的技术资讯与实用技术文章', 'IT从业者，注重实战应用，追求学习新技术', '关注内容质量，注重实战和创新，维护良好的排版和图文并茂的呈现风格', 'Week', 1.5, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('内容平台', '知乎专栏', 'https://zhuanlan.zhihu.com/', '知名问答社区的专栏平台，覆盖广泛主题，强调高质量内容分享', '期望获得有深度的解答和有洞见的文章', '广泛受众群体，包括专业人士和普通用户', '提供专业及有深度的内容，利用问题回答和话题来提升关注度', 'Week', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', 'CSDN', 'https://www.csdn.net/', '中国最大的IT社区和服务平台，主要供开发者交流学习', '寻找技术教程、博客文章、论坛讨论', '文章内容要有针对性，SEO优化，标题吸引人', '覆盖新手到资深技术人员的广泛开发者', 'Week', 2.5, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', 'SegmentFault', 'https://segmentfault.com/', '开发者技术问答平台，注重问题解答与技术分享', '专业技术问答，解决具体编程问题', '积极参与问答，分享技术见解和解决方案', '针对编程开发者，特别是Web前端和后端开发', 'onHotSpot', NULL, 4, 0, '境内'); -- 注意：suggest_times未直接给定具体数字，需根据实际情况调整或使用NULL
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', 'oschina', 'https://www.oschina.net/', '开源技术社区，促进开源文化和自由软件的传播', '掌握开源项目动态，寻找开源解决方案', '突出项目的开源特性，注重技术分享和开源精神', '开源贡献者、开发者和技术爱好者', 'Month', 1, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', 'GitHub', 'https://github.com/', '全球最大的开源平台和代码托管服务，程序员聚集地', '代码托管、协同开发、社区交流', 'README清晰详细，适时回应Issues与Pull Requests，激励社区贡献', '全球软件开发者和技术高手', 'CICD', NULL, 3, 0, '全球'); -- 注意：frequency_period和suggest_times未直接给定适合直接插入的值，需按实际情况调整或使用NULL
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('内容创作平台', '简书', 'https://www.jianshu.com/', '内容创作分享平台，注重内容质量，形式多样', '阅读质量较高的文章，包括文学、技术、生活感悟等内容区块', '广范用户群体，喜好深度阅读与高质量内容', '文章内容需有趣、有料、有深度，打造精品文章', 'Week', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术论坛社区', 'V2EX', 'https://www.v2ex.com', '技术与生活结合的社区，聚焦IT行业的最新动态与讨论', '探索最新科技资讯、技术话题深度讨论、求职与招聘信息', '关注社区热门话题，发布高质量和有价值的讨论内容', '主要是技术人员，对新技术、产品和创业高度感兴趣', 'onHotSpot', NULL, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('自由职业平台', '程序员客栈', 'https://www.proginn.com/', '面向程序员的自由职业和远程工作平台', '项目合作、技术交流、招聘信息', '发布技术文章同时附带个人能力简介，突出实际项目经验', 'IT自由职业者和寻求远程合作的企业', 'onRelease', NULL, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('文档知识分享', '语雀', 'https://www.yuque.com/', '阿里巴巴开发的知识管理平台，注重团队协作和知识共享', '搜索高质量的技术文档、学习资料', '提供详尽且有条理的文档分享，便于读者理解和查阅', '开发者、产品经理及团队协作者', 'onRelease', NULL, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术博客平台', '博客园', 'https://www.cnblogs.com/', '专业的IT技术博客平台，社区氛围浓厚', '寻找技术教程、编程经验分享', '经常更新技术文章，保持原创性和深度，积极与读者互动', '主要是技术开发者和IT爱好者', 'Week', 1.5, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术博客平台', 'iteye', 'https://www.iteye.com/', 'Java开发者社区，提供技术文章、问答等', 'Java及相关技术栈的深入文章和技术交流', '发布技术深度好文，关注热点技术话题，积极参与社区互动', '以Java及移动开发者为主', 'Week', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术新闻平台', '开发者头条', 'https://toutiao.io/', '汇聚技术新闻、技术文章的平台，强调内容的时效性和专业性', '获取最新技术资讯和行业动态', '关注行业热点和技术趋势，分享有深度和新鲜视角的技术内容', '技术开发者和对IT行业保持持续关注的读者', 'onHotspot', NULL, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术新闻社区', 'Hacker News', 'https://news.ycombinator.com/', 'Y Combinator运营的科技创业社区，讨论最新技术和创业资讯', '掌握最新技术趋势，发现创新创业项目', '启蒙创业者、投资人以及对科技创新感兴趣的用户', '内容需高质量，具有启发性，适合有深度的技术议题和创业故事', 'onRelease', NULL, 4, 0, '全球');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('开发者博客社区', 'Hashnode', 'https://hashnode.com/', '开发者创建博客的平台，注重内容所有权，以开发者为中心', '阅读和分享技术知识、开发心得', '软件开发者和技术博主，注重个人品牌建设', '个人化和品牌化的内容，注重原创性，鼓励社区互动', 'Week', 1, 4, 0, '全球');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('创业社区', 'Indie Hackers', 'https://www.indiehackers.com/', '集中在独立开发者和小型创业团体，分享成功故事和收入获取方式', '获取创业灵感，学习别人成功故事', '单打独斗的开发者、小团队创业者和微型创业者', '分享独立开发和创业的真实经历，提供具体数据和个人故事，聚焦盈利性产品开发，赚钱模式', 'onRelease', NULL, 4, 0, '全球');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('内容平台', '小专栏', 'https://xiaozhuanlan.com/', '以技术和职场发展为主的中文专栏平台', '寻求深入技术话题分析、专业成长指导', '技术从业者和希望通过专栏提升自己技能的用户', '撰写贴近实践的技术文章，专栏设置需要照顾新增读者同时维护老读者的兴趣', 'Week', 1.5, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('视频平台', 'Bilibili', 'https://www.bilibili.com/', '年轻人喜爱的视频分享平台，内容形式多样，学习区涵盖技术教程等', '观看娱乐性和教育性结合的视频，获取知识和乐趣', '年轻用户，包括学生和年轻工作者，偏爱二次元文化', '制作高质量、有教育意义又不失趣味性的视频内容，关注弹幕互动', 'Week', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('视频平台', 'acfun', 'https://www.acfun.cn/', '弹幕视频网站，拥有年轻活跃的用户群体，内容相对轻松幽默', '享受轻松愉快的视频体验，欣赏原创内容', '主要是青少年和年轻人，喜欢娱乐和幽默的视频内容', '积极参与弹幕交流，视频内容要轻松幽默，吸引年轻观众', 'Week', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术教育平台', '极客时间', 'https://time.geekbang.org/', '专注于IT领域的知识服务平台，提供专栏和视频课程', '深入学习专业技术知识、追求职业成长', 'IT从业者，尤其是希望系统提高技能的专业人士', '内容要深度专业，适合专业人士学习，呈现方式要系统化，易于学习', 'onRelease', NULL, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术教育平台', '网易云课堂', 'https://study.163.com/', '提供在线教育和职业培训，课程范围覆盖多领域', '学习职业技能，提高工作效率', '广泛的学习者群体，包括学生、职场人士等多个层次的学习者', '课程内容要与市场需求紧密结合', 'onRelease', NULL, 2, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('技术教育平台', '慕课网社区', 'https://www.imooc.com/', '提供IT技能学习的在线平台，内容以课程和社区问答为主', '获取IT技能提升的课程、参与技术问答', '主要针对程序员和希望转型的学习者，追求实战操作经验', '发布实战性强、与市场紧密结合的课程，定期更新课程，文章', 'Year', 1, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('论坛与问答', 'creatorsdaily', 'https://creatorsdaily.com', '开发者日常讨论平台，以问答和讨论为主', '寻找开发灵感、分享日常开发过程和思路', '独立开发者、创业者，注重个人体验和知识共享', '需要真实展示开发者的日常工作和思考', 'onSelfSummary', NULL, 2, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('企业服务平台', '阿里云开发者社区', 'https://developer.aliyun.com/', '针对阿里云服务的开发者平台，提供技术文章、在线问答等服务', '应与阿里云产品和服务紧密结合，强调技术深度和实际应用案例，分享时需针对性和实用性强', '云服务的使用者和潜在用户，对云计算有深入需求的企业和开发者', '按需更新，优质内容为主', 'Month', 1, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('企业服务平台', '腾讯云社区', 'https://cloud.tencent.com/developer', '腾讯云官方开发者社区，提供技术资料、博客、活动等', '结合腾讯云产品特点，分享技术案例，强调实际应用价值，内容需具备一定深度并能指导使用', '针对腾讯云用户以及对腾讯云服务感兴趣的开发者', '每周至少1次', 'Week', 1, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('企业服务平台', '华为云社区', 'https://bbs.huaweicloud.com/', '华为云服务为主的技术交流平台，包括论坛、博客和其他技术分享', '关注华为云服务的技术特点和应用案例，内容应覆盖教程、分析以及最佳实践，以实用性和专业性为主', '华为云用户，包括企业开发者和个人技术爱好者', '每月至少更新几次', 'Month', 3, 3, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('科技媒体', 'ITBear科技媒体', 'http://www.itbear.com.cn/', '针对科技行业的新闻报道和深度分析平台', '发布新闻资讯时候需及时、准确，并且提供独到的市场和技术洞察', '科技行业从业者、投资人、科技爱好者', '每日跟进行业动态', 'onHotspot', NULL, 4, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('科技媒体', 'TechWeb', 'http://www.techweb.com.cn/', '提供互联网和IT行业的新闻动态、分析评论与深度报告', '提供深入分析和原创看法，在新闻时效性和深度洞察之间保持平衡', '互联网和IT行业的专业人士、企业决策者', '每周多次，及时性强', 'onHotspot', 0, 5, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('创投媒体', '36氪', 'https://36kr.com/', '面向创业者、投资人提供的新闻信息和数据服务平台', '关注创业公司、科技创新和投融资动态，用数据和故事说话，吸引读者', '创业者、投资者以及对创新创业关注的读者', '保持每周常规更新', 'Week', 1, 0, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('科技媒体', 'IT之家', 'https://www.ithome.com/', '面向广大IT爱好者的新闻资讯和评测平台', '重点在产品评测、使用技巧和科技资讯，关注用户体验，以亲民易懂的方式表达内容', '广大科技爱好者和消费者', 'Daily with hotspot', 'onHotSpot', NULL, 0, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('科技媒体', 'InfoQ', 'https://www.infoq.cn/', '关注软件开发、IT运营与企业应用的实践和创新', '深入探讨技术主题，注重原创性和价值输出，与开发者社区保持高度互动', '开发者、技术领导者和IT专业人士', 'Week', 'Week', 1, 2, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('行业周刊', '开发者周刊', 'https://theweekly.io/', '面向开发者的行业周刊，分享行业新闻、趋势和最佳实践案例', '选择对于开发者有高价值的资讯内容，保持内容的前沿性和实用性', '软件开发者、技术管理者和对开发行业感兴趣的读者', '能落地实践的有趣内容', 'Week', 1, 5, 0, '境内');
INSERT INTO dispatch_platform (biz_type, display_name, url, description, core_value, user_tag, precautions, frequency_period, suggest_times, care_hotspot, need_vpn, area) VALUES ('论坛与问答', 'CNode', 'https://cnodejs.org/', 'Node.js专业中文社区，提供技术讨论、分享和教程', '深入了解Node.js相关技术、寻找问题解决方案', 'Node.js开发者，追求专业技术交流', '专注Node.js相关内容，技术解答要专业且有针对性', 'Week', 1, 1, 0, '境内');
-- 电鸭