# shoulder 框架内嵌了 batchController，可以直接用异步导入、导出、查询批处理（导入）记录等功能

### 上传并校验
POST http://localhost:8080/api/v1/batch/testBatchDataType/validate
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryabcdef

------WebKitFormBoundaryabcdef
Content-Disposition: form-data; name="file"; filename="batchImportTest.csv"
Content-Type: text/csv;charset=utf-8

< /Users/liuyanming/IdeaProjects/openSource/shoulder-framework-demo/demo2/src/test/resources/batchImportTest.csv
------WebKitFormBoundaryabcdef--

### 查询进度
GET http://localhost:8080/api/v1/batch/testBatchDataType/progress/1
Content-Type: application/json
