// IDEA.http工具语法：https://www.jetbrains.com/help/idea/oauth-2-0-authorization.html
# shoulder 框架内嵌了 batchController，可以直接用异步导入、导出、查询批处理（导入）记录等功能
### 下载导入模板
GET http://localhost:8080/api/v1/batch/testBatchDataType/template/download


### 上传并校验
POST http://localhost:8080/api/v1/batch/testBatchDataType/validate
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryabcdef

------WebKitFormBoundaryabcdef
Content-Disposition: form-data; name="file"; filename="batchImportTest.csv"
Content-Type: text/csv;charset=utf-8

< ./src/test/resources/batchImportTest.csv
------WebKitFormBoundaryabcdef--

> {%
    client.global.set("validate_batch_id", response.body.data);
%}

### 查询进度（校验）
GET http://localhost:8080/api/v1/batch/testBatchDataType/progress/{{validate_batch_id}}
Content-Type: application/json

### 执行处理 (导入校验通过的)
POST http://localhost:8080/api/v1/batch/testBatchDataType/advance
Content-Type: application/json

{
  "batchId": "{{validate_batch_id}}",
  "dataType": "testBatchDataType",
  "currentOperation": "upload_validate",
  "nextOperation": "import",
  "updateRepeat": false
}

> {%
    client.global.set("import_batch_id", response.body.data);
%}

### 查询进度（处理）
GET http://localhost:8080/api/v1/batch/testBatchDataType/progress/{{import_batch_id}}
Content-Type: application/json


### 列出本人最近一次导入记录
GET http://localhost:8080/api/v1/batch/testBatchDataType/record/list
Content-Type: application/json

### 列出某次导入详情列表
GET http://localhost:8080/api/v1/batch/testBatchDataType/record/detail/list?
    businessType=testBatchDataType&
    batchId={{import_batch_id}}
Content-Type: application/json


### 导出导入详情
GET http://localhost:8080/api/v1/batch/testBatchDataType/record/detail/export?
    businessType=testBatchDataType&
    batchId={{import_batch_id}}
Content-Type: application/json

### 导出测试
GET http://localhost:8080/api/v1/batch/testBatchDataType/export
Content-Type: application/json

{
}
