# user 是 demo2 编写的 controller，只需很少的代码即可拥有一个基本的 controller
###

# 查单个-id查询
GET http://localhost:8080/user/1
Content-Type: application/json


###

# 查单个-条件查询
GET http://localhost:8080/user/getOne?name=shoulder
Content-Type: application/json


###

# 查多个
POST http://localhost:8080/user/listAll?limit=20
Content-Type: application/json

{

}
###
# 查单个-条件查询
POST http://localhost:8080/user/page
Content-Type: application/json

{
  "pageNo": 1,
  "pageSize": 20
}

###

# 创建用户
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 111,
  "age": 13,
  "sex": 0,
  "name": "xxxxx",
  "level": 0,
  "birth": "2000-11-11 11:12:13",
  "groupName": "a",
  "status": "123",
  "del": 0,
  "creator": 0
}

###

# 删除用户
GET http://localhost:8080/user/logicDelete?id=111

###

# 框架-删除用户
DELETE http://localhost:8080/user/111