# 查单个-id查询
GET http://localhost:8080/user/1
Content-Type: application/json


###

# 查单个-条件查询
GET http://localhost:8080/user/getOne?name=shoulder
Content-Type: application/json


###

# 查多个
POST http://localhost:8080/user/listAll
Content-Type: application/json

{

}
###
# 查单个-条件查询
POST http://localhost:8080/user/page
Content-Type: application/json

{
  "pageNo": 1,
  "pageSize": 20
}

###

# 创建用户
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": 111,
  "age": 13,
  "sex": 0,
  "name": "xxxxx",
  "level": 0,
  "birth": "2000-11-11 11:12:13",
  "groupName": "a",
  "status": "123",
  "creator": 0
}


### 标签-查询

GET http://localhost:8080/api/v1/tags/1


### 标签-删除

DELETE http://localhost:8080/api/v1/tags/1

### 标签-新增
POST http://localhost:8080/api/v1/tags
Content-Type: application/json

{
  "bizId": "",
  "type": "type",
  "name": "name",
  "display_name": "displayName",
  "icon": "icon",
  "description": "description"
}
